name: CI Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Docker Compose
        run: |
          docker-compose up --build -d

      - name: Ejecutar pruebas
        run: |
          docker exec $(docker-compose ps -q app) npm test
