name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Docker Compose
        run: |
          docker-compose up --build -d

      - name: Ejecutar pruebas
        run: |
          docker exec $(docker-compose ps -q app) npm test

  deploy:
    needs: build  # Asegura que 'build' se ejecute antes de 'deploy'
    runs-on: ubuntu-latest
    steps:
      - name: Login en Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Construir y subir imagen a Docker Hub
        run: |
          docker build -t usuario/app:latest .
          docker tag usuario/app:latest usuario/app:v1.0.0
          docker push usuario/app:latest

      - name: Desplegar en servidor
        run: ssh eamaya@localhost "docker pull usuario/app:latest && docker-compose up -d"

